services:
  backend:
    container_name: api-tsc
    build: .
    ports:
      - "5001:5001"
    env_file:
      - .env
    restart: always


  # mongo:
  #   image: mongo:6
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - mongo_data:/data/db
  #     - /opt/nodeapps/uploads:/opt/nodeapps/uploads

# volumes:
#   mongo_data:
